"""add unique constraint on advisory cve+source_domain

Revision ID: c2fc3ba0418e
Revises: 0001_initial
Create Date: 2026-08-21 16:12:57.329794
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c2fc3ba0418e'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE INDEX IF NOT EXISTS ix_advisory_cve ON advisory (cve)')
    with op.batch_alter_table('advisory') as batch_op:
        batch_op.create_unique_constraint('uq_advisory_cve_source_domain', ['cve', 'source_domain'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisory') as batch_op:
        batch_op.drop_constraint('uq_advisory_cve_source_domain', type_='unique')
    op.drop_index(op.f('ix_advisory_cve'), table_name='advisory')
    # ### end Alembic commands ###
